//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFERA {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PatientFirstName {
            get {
                return ((string)(this["PatientFirstName"]));
            }
            set {
                this["PatientFirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PatientLastName {
            get {
                return ((string)(this["PatientLastName"]));
            }
            set {
                this["PatientLastName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PatientCopay {
            get {
                return ((string)(this["PatientCopay"]));
            }
            set {
                this["PatientCopay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InsuranceCompanyName {
            get {
                return ((string)(this["InsuranceCompanyName"]));
            }
            set {
                this["InsuranceCompanyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InsuranceCompanyTaxId {
            get {
                return ((string)(this["InsuranceCompanyTaxId"]));
            }
            set {
                this["InsuranceCompanyTaxId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BillIdPreference {
            get {
                return ((bool)(this["BillIdPreference"]));
            }
            set {
                this["BillIdPreference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReloadLastPatient {
            get {
                return ((bool)(this["ReloadLastPatient"]));
            }
            set {
                this["ReloadLastPatient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeSubscriber {
            get {
                return ((bool)(this["IncludeSubscriber"]));
            }
            set {
                this["IncludeSubscriber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Street One")]
        public string InsuranceCompanyAddressLineOne {
            get {
                return ((string)(this["InsuranceCompanyAddressLineOne"]));
            }
            set {
                this["InsuranceCompanyAddressLineOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Street Two")]
        public string InsuranceCompanyAddressLineTwo {
            get {
                return ((string)(this["InsuranceCompanyAddressLineTwo"]));
            }
            set {
                this["InsuranceCompanyAddressLineTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("City")]
        public string InsuranceCompanyAddressCity {
            get {
                return ((string)(this["InsuranceCompanyAddressCity"]));
            }
            set {
                this["InsuranceCompanyAddressCity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AL")]
        public string InsuranceCompanyAddressState {
            get {
                return ((string)(this["InsuranceCompanyAddressState"]));
            }
            set {
                this["InsuranceCompanyAddressState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99991")]
        public string InsuranceCompanyAddressZipCode {
            get {
                return ((string)(this["InsuranceCompanyAddressZipCode"]));
            }
            set {
                this["InsuranceCompanyAddressZipCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Street One")]
        public string BillingProviderAddressLineOne {
            get {
                return ((string)(this["BillingProviderAddressLineOne"]));
            }
            set {
                this["BillingProviderAddressLineOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Street Two")]
        public string BillingProviderAddressLineTwo {
            get {
                return ((string)(this["BillingProviderAddressLineTwo"]));
            }
            set {
                this["BillingProviderAddressLineTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("City")]
        public string BillingProviderAddressCity {
            get {
                return ((string)(this["BillingProviderAddressCity"]));
            }
            set {
                this["BillingProviderAddressCity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AL")]
        public string BillingProviderAddressState {
            get {
                return ((string)(this["BillingProviderAddressState"]));
            }
            set {
                this["BillingProviderAddressState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public string BillingProviderAddressZipCode {
            get {
                return ((string)(this["BillingProviderAddressZipCode"]));
            }
            set {
                this["BillingProviderAddressZipCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BillingProviderName {
            get {
                return ((string)(this["BillingProviderName"]));
            }
            set {
                this["BillingProviderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BillingProviderFirstName {
            get {
                return ((string)(this["BillingProviderFirstName"]));
            }
            set {
                this["BillingProviderFirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BillingProviderLastName {
            get {
                return ((string)(this["BillingProviderLastName"]));
            }
            set {
                this["BillingProviderLastName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BillingProviderNpi {
            get {
                return ((string)(this["BillingProviderNpi"]));
            }
            set {
                this["BillingProviderNpi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RenderingProviderFirstName {
            get {
                return ((string)(this["RenderingProviderFirstName"]));
            }
            set {
                this["RenderingProviderFirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RenderingProviderLastName {
            get {
                return ((string)(this["RenderingProviderLastName"]));
            }
            set {
                this["RenderingProviderLastName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RenderingProviderNpi {
            get {
                return ((string)(this["RenderingProviderNpi"]));
            }
            set {
                this["RenderingProviderNpi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReusePatient {
            get {
                return ((bool)(this["ReusePatient"]));
            }
            set {
                this["ReusePatient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableReusePatientPrompt {
            get {
                return ((bool)(this["EnableReusePatientPrompt"]));
            }
            set {
                this["EnableReusePatientPrompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReuseAddon {
            get {
                return ((bool)(this["ReuseAddon"]));
            }
            set {
                this["ReuseAddon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableReuseAddonPrompt {
            get {
                return ((bool)(this["EnableReuseAddonPrompt"]));
            }
            set {
                this["EnableReuseAddonPrompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BillingProviderIsIndividual {
            get {
                return ((bool)(this["BillingProviderIsIndividual"]));
            }
            set {
                this["BillingProviderIsIndividual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public string PatientPlaceOfService {
            get {
                return ((string)(this["PatientPlaceOfService"]));
            }
            set {
                this["PatientPlaceOfService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReuseChargeForNextPatient {
            get {
                return ((bool)(this["ReuseChargeForNextPatient"]));
            }
            set {
                this["ReuseChargeForNextPatient"] = value;
            }
        }
    }
}
